default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 123
  host: localhost
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: presentacion_development

test:
  <<: *default
  database: presentacion_test

production:
  <<: *default
  database: mysql://b22ffddb7d7285:f018bf7f@eu-cdbr-west-01.cleardb.com/heroku_19fb9080436b66f?reconnect=true
  adapter: mysql2
  username: root
  password: 123
