default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 123
  host: localhost
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: presentacion_development

test:
  <<: *default
  database: presentacion_test

production:
  <<: *default
  database: ENV['CLEARDB_DATABASE_URL']
  username: ENV['CLEARDB_DATABASE_USERNAME']
  password: ENV['CLEARDB_DATABASE_PASSWORDs']
