
<% socket_locations = %w[/opt/local/var/run/mysql5/mysqld.sock /var/lib/mysql/mysql.sock /tmp/mysql.sock] %>

default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 123
  host: localhost
  socket: <%= socket_locations.detect { |f| File.exists?(f) } %>

development:
  <<: *default
  database: presentacion_development

test:
  <<: *default
  database: presentacion_test

production:
  <<: *default
  database: presentacion_production
